title: Visual Essay of the Palouse (using Juncture)
tagline: That's a whole lotta hill!
description: Just testing the Juncture Visual essay framework on a Friday afternoon.
banner: https://upload.wikimedia.org/wikipedia/commons/a/a0/Palouse_hills_northeast_of_Walla_Walla.jpg
#favicon: <favicon url>
#logo: <logo url>

# When using a custom domain these fields must be updated to match
# the Github account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: Contact the Juncture team
  icon: fas fa-envelope
  action: contact-us
- label: View page source
  icon: fas fa-file-code
  action: view-markdown
- label: A Palouse view
  icon: fas fa-file-code
  action: load-page
  path: /palouse 
# If a contact-us action is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
contactForm:
  to:
  - JSTOR Labs <labs@ithaka.org>
  subject: Juncture
